accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLogInView.as_view(), name='user_login'),
    path('logout/', views.UserLogOutView.as_view(), name='user_logout'),

    path('profile/<int:user_id>/', views.UserProfileView.as_view(),
                                            name='user_profile'),

    path('password_reset/', views.UserPasswordResetView.as_view(),
                                            name='password_reset'),

    path('password_reset/done/', views.UserPasswordResetDoneView.as_view(),
                                            name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
                                            views.UserPasswordResetConfirmView.as_view(),
                                            name='password_reset_confirm'),

    path('password_reset/complete', views.UserPasswordResetCompleteView.as_view(),
                                            name='password_reset_complete'),
    
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),

    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('post/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='home')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsPageView.as_view(), name='posts_list'),
    path('<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like-dislike/<int:post_id>/', views.PostLikeDislikeView.as_view(), name='post_like'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Relation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} following {self.to_user}'
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField(default=0)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username
    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Profile


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()

        if user:
            raise ValidationError('This Email Already Exists')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()

        if user:
            raise ValidationError('This username Already Exists')
        return username

    def clean(self):
        cd = super().clean()
        pass1 = cd.get('password1')
        pass2 = cd.get('password2')

        if pass1 and pass2 and len(pass1) <= 8:
            raise ValidationError("Password must be more than 8 character")

        if pass1 != pass2:
            raise ValidationError("Password Does'nt match together")


class UserLogInForm(forms.Form):
    username = forms.CharField(label='username or email:', widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))


class EditUserForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = Profile
        fields = ('age', 'bio')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


from .forms import UserRegistrationForm, UserLogInForm, EditUserForm
from .models import Relation, Profile


class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.warning(request, f'you are now logged in as {request.user.username}')
            return redirect('pages:home')
        return super().dispatch(request, *args, **kwargs)
    

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password1'])
            messages.success(request, 'you registered successfully', 'success')
            return redirect('accounts:user_login')
        return render(request, self.template_name, {'form' : form})


class UserLogInView(View):
    form_class = UserLogInForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.warning(request, f'you are now logged in as {request.user.username}')
            return redirect('pages:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'You are successfully logged in', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('pages:home')
            messages.error(request, 'Wrong password or username', 'danger')
        return render(request, self.template_name, {'form':form})  


class UserLogOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you are logged out successfully', 'success')
        return redirect('pages:home')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        is_following = False
        user = get_object_or_404(User, pk=user_id)
        posts = user.posts.all()
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            is_following = True
        return render(request, 'accounts/profile.html', {'user':user, 'posts':posts, 'is_following':is_following})



class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(request, "you are already following this user")
        else:
            Relation(from_user=request.user, to_user=user).save()
            messages.success(request, 'you followed this user')
        return redirect('accounts:user_profile', user.id)


class UserUnfollowView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request, "you unfollowed this user")
        else:
            messages.error(request, 'you are not following this user')
        return redirect('accounts:user_profile', user.id)


class EditUserView(LoginRequiredMixin, View):
    form_class = EditUserForm

    def get(self, request):
        form = self.form_class(instance=request.user.profile, initial={'email':request.user.email})
        return render(request, 'accounts/edit_profile.html', {'form':form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.save()
            messages.success(request, 'your profile edited successfully')
        return redirect('accounts:user_profile', request.user.id)

accounts/templates/accounts/edit_profile.html
{% extends '_base.html' %}

{% block page_title %}Edit Profile{% endblock page_title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends '_base.html' %}

{% block page_title %}LogIn{% endblock page_title %}

{% block content %}
    <h1>LogIn</h1>
    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login">
    </form>
{% endblock content %}

accounts/templates/accounts/password_reset_complete.html
{% extends '_base.html' %}

{% block page_title %}Password Changed{% endblock page_title %}

{% block content %}
    <h4>Your password changed successfully.</h4>
{% endblock content %}

accounts/templates/accounts/password_reset_confirm.html
{% extends '_base.html' %}

{% block page_title %}Password Reset Confirm{% endblock page_title %}

{% block content %}
    {% if validlink %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Change">
        </form>
    {% else %}
        <p>This is not valid link, please try later.</p>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/password_reset_done.html
{% extends '_base.html' %}

{% block page_title %}Password Reset Done{% endblock page_title %}

{% block content %}
    <h4>We send you an email.</h4>
{% endblock content %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends '_base.html' %}

{% block page_title %}Password Reset{% endblock page_title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends '_base.html' %}

{% block page_title %}Profile{% endblock page_title %}

{% block content %}
    <h3 class="text-center">{{ user.username }}</h3>
    <p>Bio: {{ user.profile.bio }}</p>
    <p>Age: {{ user.profile.age }}</p>
    <p>Email: {{ user.email }}</p>
    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:8 }}</a>
        {% endfor %}
    </div>
        {% if request.user.id == user.id %}
            <a href="{% url 'posts:post_create' %}" class="btn btn-primary mt-3">New Post</a>
            <a href="{% url 'accounts:edit_user' %}" class="btn btn-info mt-3">Edit</a>
        {% endif %}
        {% if request.user.id != user.id and not is_following %}
            <a href="{% url 'accounts:user_follow' user.id %}" class="btn btn-primary mt-3">Follow</a>
        {% elif request.user.id != user.id and is_following %}
            <a href="{% url 'accounts:user_unfollow' user.id %}" class="btn btn-danger mt-3">UnFollow</a>
        {% endif %}
{% endblock content %}

accounts/templates/accounts/register.html
{% extends '_base.html' %}

{% block page_title %}Register{% endblock page_title %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock content %}