accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLogInView.as_view(), name='user_login'),
    path('logout/', views.UserLogOutView.as_view(), name='user_logout'),

    path('profile/<int:user_id>/', views.UserProfileView.as_view(),
                                            name='user_profile'),

    path('password_reset/', views.UserPasswordResetView.as_view(),
                                            name='password_reset'),

    path('password_reset/done/', views.UserPasswordResetDoneView.as_view(),
                                            name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
                                            views.UserPasswordResetConfirmView.as_view(),
                                            name='password_reset_confirm'),

    path('password_reset/complete', views.UserPasswordResetCompleteView.as_view(),
                                            name='password_reset_complete'),
    
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),

    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('post/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='home')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsPageView.as_view(), name='posts_list'),
    path('<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like-dislike/<int:post_id>/', views.PostLikeDislikeView.as_view(), name='post_like'),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" aria-current="page" href="{% url 'pages:home' %}">Home</a>
          <a class="nav-link" aria-current="page" href="{% url 'posts:posts_list' %}">Posts</a>
          {% if request.user.is_authenticated %}
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user_profile' request.user.id %}">Profile</a>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user_logout' %}">LogOut</a>
          {% else %}
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user_register' %}">Register</a>
            <a class="nav-link" aria-current="page" href="{% url 'accounts:user_login' %}">LogIn</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>