accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLogInView.as_view(), name='user_login'),
    path('logout/', views.UserLogOutView.as_view(), name='user_logout'),

    path('profile/<int:user_id>/', views.UserProfileView.as_view(),
                                            name='user_profile'),

    path('password_reset/', views.UserPasswordResetView.as_view(),
                                            name='password_reset'),

    path('password_reset/done/', views.UserPasswordResetDoneView.as_view(),
                                            name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
                                            views.UserPasswordResetConfirmView.as_view(),
                                            name='password_reset_confirm'),

    path('password_reset/complete', views.UserPasswordResetCompleteView.as_view(),
                                            name='password_reset_complete'),
    
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),

    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('post/', include('posts.urls', namespace='posts')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomepageView.as_view(), name='home')
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostsPageView.as_view(), name='posts_list'),
    path('<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like-dislike/<int:post_id>/', views.PostLikeDislikeView.as_view(), name='post_like'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-updated',)

    def __str__(self):
        return self.slug

    def get_absolute_url(self):
        return reverse("posts:post_detail", args=(self.id, self.slug))

    def likes_count(self):
        return self.plikes.count()

    def user_can_like(self, user):
        user_like = user.ulikes.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments',
                                blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user} - {self.body[:30]}'
    

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ulikes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='plikes')

    def __str__(self):
        return f"{self.user} liked {self.post.slug}"
    
    
    

posts/forms.py
from django import forms

from . models import Post, Comment


class CreateUpdatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body' : forms.Textarea(attrs={'class':'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        labels={
            'body':False
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].widget = forms.TextInput(attrs={'class':'form-control'})


class PostSearchForm(forms.Form):
    search = forms.CharField()

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from . models import Post, Comment, Like
from . forms import CreateUpdatePostForm, CommentCreateForm, CommentReplyForm, PostSearchForm


class PostsPageView(View):
    form_class = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__icontains=request.GET['search'])
        return render(request, 'posts/posts_view.html', {'posts':posts, 'form':self.form_class})

class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, id=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        return render(request, 'posts/post_detail.html', {
            'post':self.post_instance,
            'comments':comments,
            'form':self.form_class,
            'form_reply':self.form_class_reply,
            'can_like':can_like,
            })
    
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'Your comment submitted successfully')
            return redirect('posts:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        if request.user.id == post.user.id:
            post.delete()
            messages.success(request, 'Your post deleted successfully')
        else:
            messages.error(request, 'You cant delete this post')
        
        return redirect('pages:home')


class PostUpdateView(LoginRequiredMixin,View):
    form_class = CreateUpdatePostForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if post.user.id != request.user.id:
            messages.error(request, 'you cant update this post')
            return redirect('pages:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'posts/post_update.html', {'form':form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST,instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'you updated post successfully')
            return redirect('posts:post_detail', new_post.id, new_post.slug)


class PostCreateView(LoginRequiredMixin, View):
    form_class = CreateUpdatePostForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'posts/post_create.html', {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request, 'you create new post successfully')
            return redirect('posts:post_detail', new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=kwargs['post_id'])
        comment = get_object_or_404(Comment, id=kwargs['comment_id'])
        form = self.form_class(request.POST)

        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply is submitted successfully.')
        return redirect('posts:post_detail', post.id, post.slug)



class PostLikeDislikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, id=post_id)
        like = Like.objects.filter(post=post, user=request.user)

        if like.exists():
            like.delete()
            messages.success(request, 'you have already disliked this post.')
        else:
            Like.objects.create(post=post, user=request.user)
            messages.success(request, 'you liked this post.')
        return redirect('posts:post_detail', post.id, post.slug)


    

posts/templates/posts/post_create.html
{% extends '_base.html' %}

{% block page_title %}Posts Create{% endblock page_title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="post">
    </form>
{% endblock content %}

posts/templates/posts/post_detail.html
{% extends '_base.html' %}

{% block page_title %}Posts Detail{% endblock page_title %}

{% block content %}
    <p><a href="{% url 'accounts:user_profile' post.user.id %}">{{ post.user.username }}</a> - {{ post.updated|date:"M Y" }} | post likes: {{ post.likes_count }}</p>
    <p>{{ post.body }}</p>
    {% if request.user.id == post.user.id %}
        <a href="{% url 'posts:post_delete' post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url 'posts:post_update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}
    
    {% if request.user.is_authenticated %}
        {% if can_like %}
            <a href="{% url 'posts:post_like' post.id %}" class="btn btn-danger col-md-2">dislike</a>
        {% else %}
            <a href="{% url 'posts:post_like' post.id %}" class="btn btn-primary col-md-2">like</a>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="send" class="btn btn-info mb-3">
        </form>
    {% else %}
        <p class="aler alert-danger">Only logged in users can leave comment.</p>
    {% endif %}

    <div class="card">
        <p class="card-header">Comments: {{ comments.count }}</p>
    </div>

    {% for comment in comments %}
        <div class="card">
            <p class="card-header bg-dark text-white">{{ comment.user }} | {{ comment.created|timesince }}</p>
            <div class="card-body">
                <p>{{ comment.body }}</p>
                {% if request.user.is_authenticated %}
                    <button class="collapsible">Reply</button>
                    <div class="content">
                        <form action="{% url 'posts:add_reply' post.id comment.id %}" method="post" class="col-md-6 p-3">
                            {% csrf_token %}
                            {{ form_reply }}
                            <input type="submit" value="send" class="btn btn-info mt-2">
                        </form>
                    </div>
                {% endif %}
            </div>

            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <div class="bg-primary p-3 m-2">
                        <p>reply form: {{ reply.user }} | {{ reply.created|timesince }} <br> {{ reply.body }}</p>
                    </div>
                {% endfor %}
            {% endwith %}
        </div>
    {% empty %}
        <p>No comments yet!</p>
    {% endfor %}
{% endblock content %}

posts/templates/posts/post_update.html
{% extends '_base.html' %}

{% block page_title %}Posts Update{% endblock page_title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="update">
    </form>
{% endblock content %}

posts/templates/posts/posts_view.html
{% extends '_base.html' %}

{% block page_title %}Posts{% endblock page_title %}

{% block content %}
    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" value="search">
    </form>
    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body|truncatewords:8 }}</a>
        {% endfor %}
    </div>
{% endblock content %}